//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandRunner.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string cancelUpdateDownloadButton {
            get {
                return ResourceManager.GetString("cancelUpdateDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new page load was not successful. Please verify that you are connected to the Internet..
        /// </summary>
        public static string changeLogRetrievalFailedMessage {
            get {
                return ResourceManager.GetString("changeLogRetrievalFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string checkForUpdateButton {
            get {
                return ResourceManager.GetString("checkForUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for update on launch.
        /// </summary>
        public static string checkForUpdateOnLaunchCheckBox {
            get {
                return ResourceManager.GetString("checkForUpdateOnLaunchCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string chooseDirButton {
            get {
                return ResourceManager.GetString("chooseDirButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear output.
        /// </summary>
        public static string clearOutputButton {
            get {
                return ResourceManager.GetString("clearOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string closeButton {
            get {
                return ResourceManager.GetString("closeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string commandLabel {
            get {
                return ResourceManager.GetString("commandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue download.
        /// </summary>
        public static string continueUpdateDownloadButton {
            get {
                return ResourceManager.GetString("continueUpdateDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy output.
        /// </summary>
        public static string copyOutputButton {
            get {
                return ResourceManager.GetString("copyOutputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update.
        /// </summary>
        public static string downloadingUpdateDialogTitle {
            get {
                return ResourceManager.GetString("downloadingUpdateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while CommandRunner update {0} is beeing downloaded..
        /// </summary>
        public static string downloadingUpdateMessage {
            get {
                return ResourceManager.GetString("downloadingUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error regular expression.
        /// </summary>
        public static string errorRegexLabel {
            get {
                return ResourceManager.GetString("errorRegexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        public static string findNextButton {
            get {
                return ResourceManager.GetString("findNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find previous.
        /// </summary>
        public static string findPreviousButton {
            get {
                return ResourceManager.GetString("findPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find text.
        /// </summary>
        public static string findTextDialogTitle {
            get {
                return ResourceManager.GetString("findTextDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what.
        /// </summary>
        public static string findWhatLabel {
            get {
                return ResourceManager.GetString("findWhatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string helpButton {
            get {
                return ResourceManager.GetString("helpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string helpDialogTitle {
            get {
                return ResourceManager.GetString("helpDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore case.
        /// </summary>
        public static string ignoreCaseCheckBox {
            get {
                return ResourceManager.GetString("ignoreCaseCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill process.
        /// </summary>
        public static string killButton {
            get {
                return ResourceManager.GetString("killButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch installer.
        /// </summary>
        public static string launchUpdateInstallerButton {
            get {
                return ResourceManager.GetString("launchUpdateInstallerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch update installer.
        /// </summary>
        public static string launchUpdateInstallerDialogTitle {
            get {
                return ResourceManager.GetString("launchUpdateInstallerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installer has been downloaded. Do you want to launch it?.
        /// </summary>
        public static string launchUpdateInstallerMessage {
            get {
                return ResourceManager.GetString("launchUpdateInstallerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        public static string notNowButton {
            get {
                return ResourceManager.GetString("notNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        public static string noUpdateAvailableDialogTitle {
            get {
                return ResourceManager.GetString("noUpdateAvailableDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of CommandRunner {0} is up to date..
        /// </summary>
        public static string noUpdateAvailableMessage {
            get {
                return ResourceManager.GetString("noUpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string outputLabel {
            get {
                return ResourceManager.GetString("outputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play error sound when regular expression matches.
        /// </summary>
        public static string playErrorSoundCheckBox {
            get {
                return ResourceManager.GetString("playErrorSoundCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play success sound when regular expression matches.
        /// </summary>
        public static string playSuccessSoundCheckBox {
            get {
                return ResourceManager.GetString("playSuccessSoundCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string runButton {
            get {
                return ResourceManager.GetString("runButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and more.
        /// </summary>
        public static string settingsButton {
            get {
                return ResourceManager.GetString("settingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and more.
        /// </summary>
        public static string settingsDialogTitle {
            get {
                return ResourceManager.GetString("settingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success regular expression.
        /// </summary>
        public static string successRegexLabel {
            get {
                return ResourceManager.GetString("successRegexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandRunner update available.
        /// </summary>
        public static string updateAvailableDialogTitle {
            get {
                return ResourceManager.GetString("updateAvailableDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New CommandRunner version {0} is available. You currently have version {1}. Do you want to download the update and run its installation now?.
        /// </summary>
        public static string updateAvailableMessage {
            get {
                return ResourceManager.GetString("updateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update failed.
        /// </summary>
        public static string updateCheckFailedDialogTitle {
            get {
                return ResourceManager.GetString("updateCheckFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update was not successful. Please verify that you are connected to the Internet..
        /// </summary>
        public static string updateCheckFailedMessage {
            get {
                return ResourceManager.GetString("updateCheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download failed.
        /// </summary>
        public static string updateDownloadFailedDialogTitle {
            get {
                return ResourceManager.GetString("updateDownloadFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download was not successful. Please verify that you are connected to the Internet..
        /// </summary>
        public static string updateDownloadFailedMessage {
            get {
                return ResourceManager.GetString("updateDownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download in progress.
        /// </summary>
        public static string updateDownloadInProgressDialogTitle {
            get {
                return ResourceManager.GetString("updateDownloadInProgressDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update is being downloaded. Do you want to cancel the download?.
        /// </summary>
        public static string updateDownloadInProgressMessage {
            get {
                return ResourceManager.GetString("updateDownloadInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update.
        /// </summary>
        public static string updateDownloadProgressLabel {
            get {
                return ResourceManager.GetString("updateDownloadProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installer is running.
        /// </summary>
        public static string updateInstallRunningDialogTitle {
            get {
                return ResourceManager.GetString("updateInstallRunningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update installer is running. Please finish or cancel the installation before downloading the update again..
        /// </summary>
        public static string updateInstallRunningMessage {
            get {
                return ResourceManager.GetString("updateInstallRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new.
        /// </summary>
        public static string whatsNewButton {
            get {
                return ResourceManager.GetString("whatsNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new in CommandRunner.
        /// </summary>
        public static string whatsNewDialogTitle {
            get {
                return ResourceManager.GetString("whatsNewDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory.
        /// </summary>
        public static string workingDirLabel {
            get {
                return ResourceManager.GetString("workingDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yesButton {
            get {
                return ResourceManager.GetString("yesButton", resourceCulture);
            }
        }
    }
}
